In [74]:
import pandas as pd
df = pd.read_csv("NLIC.csv")
df

published_date   open   high    low  close  per_change  traded_quantity  \
0        2011-03-29  725.0  725.0  725.0  725.0         NaN             60.0   
1        2011-03-31  725.0  715.0  715.0  715.0       -1.38             20.0   
2        2011-04-18  715.0  701.0  701.0  701.0       -1.96            450.0   
3        2011-04-27  701.0  701.0  701.0  701.0        0.00             30.0   
4        2011-05-02  701.0  687.0  648.0  648.0       -7.56           3083.0   
...             ...    ...    ...    ...    ...         ...              ...   
2616     2023-06-20  772.0  787.4  750.0  750.0       -2.85         150595.0   
2617     2023-06-21  760.0  760.0  737.1  746.0       -0.53         121852.0   
2618     2023-06-22  760.0  769.8  747.0  763.0        2.28         100868.0   
2619     2023-06-25  778.0  804.9  767.0  799.0        4.72         257931.0   
2620     2023-06-26  811.0  819.8  778.0  782.0       -2.13         186943.0   

      traded_amount  status  
0           43500.0       0  
1           14300.0       0  
2          315450.0       0  
3           21030.0       0  
4         2024499.0       0  
...             ...     ...  
2616    114958036.2      -1  
2617     91330330.9      -1  
2618     76635686.1       1  
2619    204758656.0       1  
2620    148639326.2      -1  

[2621 rows x 9 columns]

In [75]:
#creating series 
ser = pd.Series(['Name','Jeevan', 'Ram','shyam','Hari',])
type(ser)

pandas.core.series.Series

In [76]:
import numpy as np
ser = pd.Series(np.array([
    'Male', 'Female'
]))
type(ser)

pandas.core.series.Series

In [77]:
ser1 = pd.Series({'a':1, 'b':2, 'c':3})
type(ser1)

pandas.core.series.Series

In [78]:
ser1.index # gives the key of the dictionary if the format was dictionary

Index(['a', 'b', 'c'], dtype='object')

In [79]:
ser1.values

array([1, 2, 3], dtype=int64)

In [80]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

In [81]:
ser2 = pd.Series(list_data)

In [82]:
ser2

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [83]:
ser2.index

RangeIndex(start=0, stop=5, step=1)

In [84]:
# creating and manipulating the data in pandas

In [85]:
pd.DataFrame({"Name":["Braund, Mr. Owen Harris", "Allen, Mr. William Henry", "Bonnell, Miss. Elizabeth"], "Age":[22, 35, 58], "Sex": ['male', 'male','female']})

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [86]:
df = pd.DataFrame({"Name":["Braund, Mr. Owen Harris", "Allen, Mr. William Henry", "Bonnell, Miss. Elizabeth"], "Age":[22, 35, 58], "Sex": ['male', 'male','female']})

In [87]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [88]:
type(df['Age'])

pandas.core.series.Series

In [89]:
df['Age'][0]

22

In [90]:
# list of list into a data frame
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [92]:
df[0]

0    1
1    4
2    7
Name: 0, dtype: int64

In [93]:
type(df[0] )

pandas.core.series.Series

In [94]:
# creating a series by designating index
eye = pd.Series({"Brown":220,"Blue":215,"Hazel":93,"Green":64})

In [95]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [96]:
type(eye)

pandas.core.series.Series

In [97]:
eye.name

In [98]:
eye.name = "eye_color"

In [99]:
eye

Brown    220
Blue     215
Hazel     93
Green     64
Name: eye_color, dtype: int64

In [100]:
eye.index

Index(['Brown', 'Blue', 'Hazel', 'Green'], dtype='object')

In [101]:
eye.values

array([220, 215,  93,  64], dtype=int64)

In [102]:
eye.sort_values()

Green     64
Hazel     93
Blue     215
Brown    220
Name: eye_color, dtype: int64

In [103]:
eye.sort_index()

Blue     215
Brown    220
Green     64
Hazel     93
Name: eye_color, dtype: int64

In [104]:
eye.unique()

array([220, 215,  93,  64], dtype=int64)

In [105]:
eye.nunique()

4

In [106]:
my_data2 = [220, 215, 93, 64, 64]

In [107]:
eye2 = pd.Series(data=my_data2, index=['Brown', 'Blue','Blue', 'Hazel', 'Green'])

In [108]:
eye2

Brown    220
Blue     215
Blue      93
Hazel     64
Green     64
dtype: int64

In [109]:
eye2.unique()

array([220, 215,  93,  64], dtype=int64)

In [110]:
eye2.nunique()

4

In [111]:
eye2.value_counts() # dami 


64     2
220    1
215    1
93     1
dtype: int64

In [112]:
# series indexing and slicing 
ser = pd.Series([0,10,20,30,40], index=['a', 'b', 'c','d','e']) # index normally 0 to bata suuru hunxa we change it to something our own values 

In [113]:
ser

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [114]:
ser[1]

10

In [115]:
ser['b']

10

In [116]:
ser[1:3]

b    10
c    20
dtype: int64

In [118]:
#series operations 
ser1 = pd.Series([0,1,2,3,4], index=[0,1,2,3,4])
ser2 = pd.Series([0,1,2,3,4], index=[4,3,2,1,0])

In [119]:
ser1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [120]:
ser2

4    0
3    1
2    2
1    3
0    4
dtype: int64

In [124]:
ser1,ser2, ser1+ser2

(0    0
 1    1
 2    2
 3    3
 4    4
 dtype: int64,
 4    0
 3    1
 2    2
 1    3
 0    4
 dtype: int64,
 0    4
 1    4
 2    4
 3    4
 4    4
 dtype: int64)

In [126]:
ser1, ser2,  ser1*ser2

(0    0
 1    1
 2    2
 3    3
 4    4
 dtype: int64,
 4    0
 3    1
 2    2
 1    3
 0    4
 dtype: int64,
 0    0
 1    3
 2    4
 3    3
 4    0
 dtype: int64)

In [127]:
ser1/ser2

0    0.000000
1    0.333333
2    1.000000
3    3.000000
4         inf
dtype: float64

In [128]:
print(ser1)
ser1.sum()

0    0
1    1
2    2
3    3
4    4
dtype: int64


10

In [129]:
ser1.mean()

2.0

In [130]:
ser1.median()

2.0

In [131]:
ser1.max()

4

In [134]:
ser1.min()

0

In [136]:
ser1.std()

1.5811388300841898

In [137]:
ser1.sort_values()

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [138]:
#applying the lambda function to the series
ser_height = pd.Series([160, 170, 180], name='height')

In [139]:
ser_height

0    160
1    170
2    180
Name: height, dtype: int64

In [140]:
plus_10 = lambda x:x+10

In [141]:
plus_10(5)

15

In [142]:
ser_height.apply(lambda x:x+10)

0    170
1    180
2    190
Name: height, dtype: int64

In [145]:
print(eye)
eye.apply(plus_10)

Brown    220
Blue     215
Hazel     93
Green     64
Name: eye_color, dtype: int64


Brown    230
Blue     225
Hazel    103
Green     74
Name: eye_color, dtype: int64