In [12]:
import numpy as np
arr = np.arange(15).reshape((3,5))

In [14]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [19]:
###New 

In [22]:
arr = np.random.randn(6,3)


In [23]:
arr

array([[ 1.61557004,  2.23514871,  0.47109047],
       [ 0.24943017, -0.2179741 , -2.07349609],
       [-1.20339307, -0.43341403, -0.12935742],
       [ 0.50904535, -0.48168761, -0.32530109],
       [-1.63890371,  0.09038473,  0.10290183],
       [ 1.60511401, -1.91158802,  0.11250478]])

In [25]:
arr.T

array([[ 1.61557004,  0.24943017, -1.20339307,  0.50904535, -1.63890371,
         1.60511401],
       [ 2.23514871, -0.2179741 , -0.43341403, -0.48168761,  0.09038473,
        -1.91158802],
       [ 0.47109047, -2.07349609, -0.12935742, -0.32530109,  0.10290183,
         0.11250478]])

In [27]:
np.dot(arr.T, arr)

array([[9.64196036, 0.616588  , 0.24589879],
       [0.616588  , 9.12561129, 1.51192247],
       [0.24589879, 1.51192247, 4.66711252]])

In [33]:
arr_1 = np.arange(12).reshape(3,4)
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr_1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
arr_1.transpose((0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
import numpy as np 
arr = np.arange(16).reshape((2,2,4))
print(arr)
arr.transpose((1,0,2))


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [54]:
help(arr.swapaxes)
help(np.swapaxes)

Help on built-in function swapaxes:

swapaxes(...) method of numpy.ndarray instance
    a.swapaxes(axis1, axis2)
    
    Return a view of the array with `axis1` and `axis2` interchanged.
    
    Refer to `numpy.swapaxes` for full documentation.
    
    See Also
    --------
    numpy.swapaxes : equivalent function

Help on function swapaxes in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    ar

In [70]:
import numpy as np
arr = np.arange(12).reshape(2,2,3)
print(arr)
arr.swapaxes(1,0)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])