In [58]:
import numpy as np
arr = np.arange(1,19).reshape(6,3)
print (arr)
arr[2:3]
arr[2:,:]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [74]:
import numpy as np
names = np.array(['jk', 'jk','ram','shyam'])
names[names == "jk"]
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
print(condition)
print(arr[condition])  # Output: [4 5]
# arr2 = 


[False False False  True  True]
[4 5]


In [78]:
arr2 = np.arange(20)
arrMask = (arr2%5==0)
arr2[arrMask]
# arr2 > 10
# arrMask2 = (arr2>=10)

array([ 0,  5, 10, 15])